name: youwallet
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  web3dart: ^1.2.3
  cupertino_icons: ^0.1.2
  image_picker_saver: ^0.3.0
  http: ^0.12.0
  local_auth: ^0.6.1+3
  share: ^0.6.1+1
  #助记词生成或验证
  bip39: ^1.0.3
  bitcoin_flutter: ^1.0.7
  barcode_scan: ^3.0.1
  shared_preferences: ^0.5.4+6
  steel_crypt: ^1.5.1+1
  sqflite: ^1.0.0
  path_provider: ^1.5.1
  dart_sql: ^0.0.7
  provider: ^3.2.0
  event_bus: ^1.1.0
  #助记词密钥相关类
  ed25519_hd_key: ^1.0.1
  get_it: ^3.0.3
  common_utils: ^1.1.3
  sacco: ^0.1.0
  flutter_aes_ecb_pkcs5: ^0.1.1
#  url_launcher: ^5.4.1
  groovin_material_icons: ^1.1.6
  fluttertoast: ^3.1.3
  flutter_slidable: ^0.5.4
  dio: ^3.0.9
  decimal: ^0.3.0
  hex: ^0.1.2
#  flutter_bugly: ^0.2.8
  flutter_spinkit: ^4.1.2
  #吐司
  oktoast: ^2.3.2
  #二维码识别
  qr_flutter: ^3.2.0
  #扫一扫
  qr_code_scanner: ^0.0.12
  #手机震动
  vibration: ^1.2.3
  #声音播放器
  flutter_sound: ^2.1.1
  #图片选择器
  image_picker: ^0.6.2
  #图片裁剪
  image_cropper: ^1.2.1
  #二维码图片识别
  r_scan: ^0.1.3+2
  #下拉刷新
  pull_to_refresh: ^1.5.8
  #webView插件
#  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - locale/i18n_en.json
    - locale/i18n_zh.json
    - locale/i18n_ja.json
    - assets/images/logo.png
    - assets/images/home.png
    - assets/images/home-active.png
    - assets/images/icon.png
    - assets/
    - TempMatch.json
    - init.js
    - trust.js
    - trust_init.js
    - images/new_wallet.png
    - images/fingerprint.png
    - images/tab_wallet_active.png
    - images/tab_wallet.png
    - images/tab_exchange_active.png
    - images/tab_exchange.png
    - images/tab_receive_active.png
    - images/tab_receive.png
    - images/tab_transfer_active.png
    - images/tab_transfer.png
    - images/qrcode.png
    - images/backup.png
    - images/icon.png
    - images/qrcode.jpeg
    - images/homebk.png
    - images/homebk-full.png
    - images/splash.jpeg
    - images/empty.png
    - images/logo.png
    - images/
    - images/icon_arrow_down.png
    - sound/
    - fonts/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
